#!/bin/bash


#source_id (posts): actually 29908
actor_id__file=/tmp/how__source_id
find . -type f -iname posts*.json -exec jq '.posts[].actor_id' {} \; | sed 's/"//g' | uniq > ${source_id__file}
echo "posts actor_id: $(cat ${actor_id__file} | wc -l)"

#fromid (comments): actually 7893
fromid__file=/tmp/how__fromid
find . -type f -iname *comments.json -exec jq '.comments.comment_data[].fromid' {} \; | sed 's/"//g' | uniq > ${fromid__file}
echo "comments fromid: $(cat ${fromid__file} | wc -l)"

echo "uniqs: $(cat ${fromid__file} ${actor_id__file} | uniq | wc -l)"

#actually
#comments fromid: 7893
#posts actor_id: 29908
#uniqs: 37801
