package net.iubris.facri._ishtaran;

import javax.inject.Inject;

import net.iubris.facri.gui.actionevents.graphgeneration.Interactions.graphstream.MyFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent;
import net.iubris.facri.gui.actionevents.graphgeneration.Interactions.graphstream.MyFriendsWithMeAndTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent;
import net.iubris.facri.gui.actionevents.graphgeneration.Interactions.graphstream.MyFriendsWithMeInteractionsGraphstreamGenerationButtonCommandActionEvent;
import net.iubris.facri.gui.actionevents.graphgeneration.Interactions.graphstream.MyFriendsWithTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent;
import net.iubris.facri.gui.actionevents.parse.ParseButtonCommandActionEvent;
import net.iubris.ishtaran.gui._di.providers.AbstractCommandActionEventsHandlerProvider;

public class FacriCommandActionEventsHandlerProvider extends AbstractCommandActionEventsHandlerProvider {


	@Inject
	public FacriCommandActionEventsHandlerProvider(
			/*StemButtonCommandActionEvent stemButtonCommandActionEvent, 
			MultigraphsButtonCommandActionEvent multigraphsButtonCommandActionEvent,
			MiningButtonCommandActionEvent miningButtonCommandActionEvent*/
			ParseButtonCommandActionEvent parseButtonCommandActionEvent
			,MyFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent myFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
			,MyFriendsWithMeInteractionsGraphstreamGenerationButtonCommandActionEvent myFriendsWithMeInteractionsGraphstreamGenerationButtonCommandActionEvent
			,MyFriendsWithTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent myFriendsWithTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
			,MyFriendsWithMeAndTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent myFriendsWithMeAndTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
			) {
		super(parseButtonCommandActionEvent 
				
				,myFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
				,myFriendsWithMeInteractionsGraphstreamGenerationButtonCommandActionEvent 
				,myFriendsWithTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
				,myFriendsWithMeAndTheirFriendsInteractionsGraphstreamGenerationButtonCommandActionEvent
				
				);
	}
	
}
